services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      books:
        ipv4_address: 172.21.0.2
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - databasedata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      books:
        ipv4_address: 172.21.0.3
volumes:
  logvolume01:
  databasedata:
networks:
  books:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24